<div id="heritage">
    <h1>Our Heritage</h1>

    <div class="section">
        <p class="p1">For over 35 years, the Institute for Creation Research has distinguished itself as the leader in creation science research and education. Founded in 1970 by Dr. Henry M. Morris, ICR's vision to uncover and present evidences for the accuracy and authority of the Bible continues to lead the efforts of ICR's ministry teams. A scientist and biblical apologist, Dr. Morris is considered by many to be the father of the modern creation science movement. And yet, as many of his colleagues would attest, Dr. Morris was a man of great spiritual passion, deeply devoted to the will of God, which he continually discovered as reaching far beyond the obvious battle against evolutionary science.</p>

        <p class="p2">ICR's educational strategy from its inception has been to train future scientists who would firmly hold to the foundation of biblical creationism and then passionately communicate that belief to fellow researchers and students within their spheres of influence. The vision is one of continual transference of biblical and scientific knowledge from generation to generation. While other organizations have had great success in teaching the masses within the Church, ICR's approach has been its focus on Christian leaders, whether in science, education, ministry, or the marketplace.</p>

        <p class="p3">The outreach of ICR began with graduate-level research and education, offering Master of Science degrees in the fields of astronomy and geophysics, biology, geology, and science education. Additionally, ICR scientists lead domestic and international field study tours to the Galapagos Islands, Yosemite National Park, the Grand Canyon, Mount St. Helens, and other destinations relevant to uncovering scientific data in support of biblical creationism. Conferences and seminars, such as the popular RATE conferences on radiometric dating and Genesis presentations, allow participants to hear first-hand from ICR researchers how science verifies the biblical account of creation. ICR's radio outreach includes Science, Scripture, and Salvation and Back to Genesis in its weekly line-up of Bible and science programming on 1,700 stations. The Spanish-language program De Regreso a Genesis airs in the United States and in Latin America.</p>

        <p class="p4">Publications from ICR include a free monthly newsletter, Acts &amp; Facts, a daily devotional guide, Days of Praise, and numerous books, pamphlets, DVDs, and audio resources translated into over 25 languages.</p>

        <p class="p5">An expansion of ICR's outreach, the Henry M. Morris Center for Christian Leadership is a new strategic ministry arm of ICR, tasked with continuing the vision of Dr. Morris in the areas of professional development, new technologies, and educational coalitions&#151;all within a framework of biblical creationism.</p>
    </div>
</div>
