<div id="intro">
    <h1>Please Tell Us Who You Are</h1>

    <form name="data" method="post" action="/login.php">
    <table>
      <tr>
        <td>First name:</td><td><input type="text" name="first" size="10" /></td>
        <td>Last name:</td><td><input type="text" name="last" size="10" /></td>
        <td><input type="submit" value="Submit" /></td>
      </tr>
    </table> 
    </form>
</div>
