<div id="research">
    <h1>Research</h1>

    <div class="section">
        <p class="p1">The Institute for Creation Research Graduate School has a unique statement of faith for its faculty and students, incorporating most of the basic Christian doctrines in a creationist framework, organized in terms of two parallel sets of tenets, related to God's created world and God's inspired Word, respectively. Reproduced below are the ICR Educational Philosophy and its Tenets of Scientific Creationism and Biblical Creationism.</p>
    </div>
</div>


<div id="philosophy">
    <h1>ICR Educational Philosophy</h1>

    <div class="section">
        <p class="p1">The programs and curricula of the Graduate School, as well as the activities of other ICR divisions, while similar in factual content to those of other graduate colleges, are distinctive in one major respect. The Institute for Creation Research bases its educational philosophy on the foundational truth of a personal Creator-God and His authoritative and unique revelation of truth in the Bible, both Old and New Testaments.</p>

        <p class="p2">This perspective differs from the evolutionary humanistic philosophy which has dominated most educational institutions for the past century, providing the most satisfying and meaningful structure of a consistently creationist and Biblical framework, and placing the real facts of science and history in the best context for effective future research and application.</p>

        <p class="p3">More explicitly, the administration and faculty of ICR are committed to the tenets of both scientific creationism and Biblical creationism as formulated below. A clear distinction is drawn between scientific creationism and Biblical creationism but it is the position of the Institute that the two are compatible and that all genuine facts of science support the Bible. ICR maintains that scientific creationism should be taught along with the scientific aspects of evolutionism in tax-supported institutions, and that both scientific and Biblical creationism should be taught in Christian schools.</p>
    </div>
</div>


<div id="tenetsScientific">
    <h1>Tenets of Scientific Creationism</h1>

    <div class="bulletsection">
        <ul>
        <li>The physical universe of space, time, matter, and energy has not always existed, but was supernaturally created by a transcendent personal Creator who alone has existed from eternity.</li>
        <li>The phenomenon of biological life did not develop by natural processes from inanimate systems but was specially and supernaturally created by the Creator.</li>
        <li>Each of the major kinds of plants and animals was created functionally complete from the beginning and did not evolve from some other kind of organism. Changes in basic kinds since their first creation are limited to "horizontal" changes (variations) within the kinds, or "downward' changes (e.g., harmful mutations, extinctions).</li>
        <li>The first human beings did not evolve from an animal ancestry, but were specially created in fully human form from the start. Furthermore, the "spiritual" nature of man (self-image, moral consciousness, abstract reasoning, language, will, religious nature, etc.) is itself a supernaturally created entity distinct from mere biological life.</li>
        <li>The record of earth history, as preserved in the earth's crust, especially in the rocks and fossil deposits, is primarily a record of catastrophic intensities of natural processes, operating largely within uniform natural laws, rather than one of gradualism and relatively uniform process rates. There are many scientific evidences for a relatively recent creation of the earth and the universe, in addition to strong scientific evidence that most of the earth's fossiliferous sedimentary rocks were formed in an even more recent global hydraulic cataclysm.</li>
        <li>Processes today operate primarily within fixed natural laws and relatively uniform process rates, but since these were themselves originally created and are daily maintained by their Creator, there is always the possibility of miraculous intervention in these laws or processes by their Creator. Evidences for such intervention should be scrutinized critically, however, because there must be clear and adequate reason for any such action on the part of the Creator.</li>
        <li>The universe and life have somehow been impaired since the completion of creation, so that imperfections in structure, disease, aging, extinctions, and other such phenomena are the result of "negative" changes in properties and processes occurring in an originally-perfect created order.</li>
        <li>Since the universe and its primary components were created perfect for their purposes in the beginning by a competent and volitional Creator, and since the Creator does remain active in this now-decaying creation, there do exist ultimate purposes and meanings in the universe. Teleological considerations, therefore, are appropriate in scientific studies whenever they are consistent with the actual data of observation. Furthermore, it is reasonable to assume that the creation presently awaits the consummation of the Creator's purpose.</li>
        <li>Although people are finite and scientific data concerning origins are always circumstantial and incomplete, the human mind (if open to possibility of creation) is able to explore the manifestations of that Creator rationally, scientifically, and teleologically.</li>
        </ul>
    </div>
</div>


<div id="tenetsBiblical">
    <h1>Tenets of Biblical Creationism</h1>

    <div class="bulletsection">
        <ul>
        <li>The Creator of the universe is a triune God: Father, Son, and Holy Spirit.* There is only one eternal and transcendent God, the source of all being and meaning, and He exists in three Persons, each of whom participated in the work of creation.</li>
        <li>The Bible, consisting of the thirty-nine canonical books of the Old Testament and the twenty-seven canonical books of the New Testament, is the divinely-inspired revelation of the Creator to man. Its unique, plenary, verbal inspiration guarantees that these writings, as originally and miraculously given, are infallible and completely authoritative on all matters with which they deal, free from error of any sort, scientific and historical as well as moral and theological.</li>
        <li>All things in the universe were created and made by God in the six literal days of the Creation Week described in Genesis 1:1-2:3, and confirmed in Exodus 20:8-11. The creation record is factual, historical, and perspicuous; thus all theories of origins or development which involve evolution in any form are false. All things which now exist are sustained and ordered by God's providential care. However, a part of the spiritual creation, Satan and his angels, rebelled against God after the creation and are attempting to thwart His divine purposes in creation.</li>
        <li>The first human beings, Adam and Eve, were specially created by God, and all other men and women are their descendants. In Adam, mankind was instructed to exercise "dominion" over all other created organisms, and over the earth itself (an implicit commission for true science, technology, commerce, fine art, and education) but the temptation by Satan and the entrance of sin brought God's curse on that dominion and on mankind, culminating in death and separation from God as the natural and proper consequence.</li>
        <li>The Biblical record of primeval earth history in Genesis 1-11 is fully historical and perspicuous, including the creation and Fall of man, the Curse on the Creation and its subjection to the bondage of decay, the promised Redeemer, the worldwide cataclysmic deluge in the days of Noah, the post-diluvian renewal of man's commission to subdue the earth (now augmented by the institution of human government) and the origin of nations and languages at the tower of Babel.</li>
        <li>The alienation of man from his Creator because of sin can only be remedied by the Creator Himself, who became man in the person of the Lord Jesus Christ, through miraculous conception and virgin birth. In Christ we are indissolubly united perfect sinless humanity and full deity, so that His substitutionary death is the only necessary and sufficient price of man's redemption. That the redemption was completely efficacious is assured by His bodily resurrection from the dead and ascension into heaven; the resurrection of Christ is thus the focal point of history, assuring the consummation of God's purposes in creation.</li>
        <li>The final restoration of creation's perfection is yet future, but individuals can immediately be restored to fellowship with their Creator, on the basis of His redemptive work on their behalf, receiving forgiveness and eternal life solely through personal trust in the Lord Jesus Christ, accepting Him not only as estranged Creator but also as reconciling Redeemer and coming King. Those who reject Him, however, or who neglect to believe on Him, thereby continue in their state of rebellion and must ultimately be consigned to the everlasting fire prepared for the devil and his angels.</li>
        <li>The eventual accomplishment of God's eternal purposes in creation, with the removal of His curse and the restoration of all things to divine perfection, will take place at the personal bodily return to Earth of Jesus Christ to judge and purge sin and to establish His eternal kingdom.</li>
        <li>Each believer should participate in the "ministry of reconciliation," by seeking both to bring individuals back to God in Christ (the "Great Commission") and to "subdue the earth" for God's glory (the Edenic-Noahic Commission). The three institutions established by the Creator for the implementation of His purposes in this world (home, government, church) should be honored and supported as such.</li>
        </ul>

        <p class="note">*The Holy Spirit is one of the three divine Persons of the Holy Trinity -- one God in three persons. His ministry is to convict, regenerate, indwell, instruct, and guide all believers in Christ.</p>
    </div>
</div>


<div id="final">
    <div class="section">
        <p class="p1">In addition to a firm commitment to creationism and to full Biblical inerrancy and authority, the ICR Graduate School is committed to traditional education and to high standards of academic excellence. Each student's graduate program will consist predominantly of classroom lecture courses, with interaction between instructors and students, plus a research investigation and M.S. thesis. ICR's highly qualified and experienced faculty is in itself assurance of a rigorous and creative educational experience for its graduates, equipping them both for productive careers in their chosen fields and for making a significant contribution to the ongoing worldwide revival of theistic creationism.</p>
    </div>
</div>
